### ISSUE TITLE
Make `<time> in <location>` command smarter

### ISSUE THREAD

**Issue by ryandao** [ryandao/hubot-timezone#2]
Currently it activates for every hubot command that has the word `in` in it. It should only listen to time-related commands.

**Comment by beauraF** [comment]
Hi,

Where are you in this issue?
Because it poses problems with this script: https://github.com/jsolis/hubot-forecastio

Where each application I have this output:

> Jeeves weather in Lille
> 
> Time in Lille, France is Wednesday, December 31st 1969, 11:00:00 pm
> In Lille, France, it is currently 16.74. Feels like 16.74. Drizzle until this afternoon, starting again this evening.

Instead of:

> Jeeves weather in Lille 
> 
> In Lille, France, it is currently 16.74. Feels like 16.74. Drizzle until this afternoon, starting again this evening.

May be check above the "in" is a proper value would already be a good start and solve a bit this issue.

Thank you in advance :)

**Comment by ryandao** [comment]
I have some ideas on how to implement it but not the time to do it yet. I'll try to carve out some time for that soon.

**Comment by ryandao** [comment]
@beauraF i've pushed a fix in v1.0.1. Can you test it out?

**Comment by beauraF** [comment]
It's okay for my usage ! 
Thank you very much dude.
